import Head from 'next/head'
import Script from 'next/script'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'

export default function Home() {
  const img = "/homeimg2.jpg";
  return (
    <div className={styles.container}>
         <style jsx>
          {`
              .part1{
                background-image: url(${img});
                background-size: cover;
                padding-top:0px;
                margin-top:0 px;
              }

              .title1{
                padding-top:47px;
              }

              .blogg{
                display:flex;
                justify-content:centre;
              }

          `}
        </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, blog, hunting coder blog, next js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <div className="part1">

      <main className={styles.main}>
        <h1 className="title1">
          <span className='myspan'>Hunting Coder</span>
        </h1>

        {/* <Image className={styles.myImg} src="/homeimg.jpg" width={237} height={158} /> */}

        <p className={styles.description}>
          A Blog for Hunting coders by the hunting coder
        </p>

        </main>

        </div>

        <div className="blogitem">

        <div>
          <h2 className='blogg'>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is language used to design logic for the web.</p>
          </div>  
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is language used to design logic for the web.</p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is language used to design logic for the web.</p>
          </div>
        </div>

        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is language used to design logic for the web.</p>
          </div>
        </div>

        </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright @ Coding hunters
          {/* Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  )
}
